services:
  - type: web
    name: tg-ads-bot-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python ads/main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        value: "8603872187"
      - key: OWNER_IDS
        value: "8603872187,7748687016,7634814139,8482079412"
      - key: WEB_HOST
        value: 0.0.0.0
      - key: WEB_USERNAME
        value: admin
      - key: WEB_PASSWORD
        value: admin
